# Generated by Django 3.2 on 2021-04-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, db_index=True, to='api.ItemSize', verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='ostatok',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ostatok_item', to='api.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='ostatok',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ostatok_size', to='api.itemsize', verbose_name='Размер'),
        ),
    ]
