# Generated by Django 3.2 on 2021-04-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210423_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
