# Generated by Django 3.2 on 2021-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cartitem_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL (для главной страницы - / , для остальных - /name)'),
        ),
    ]
