# Generated by Django 3.2 on 2021-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210424_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offerText',
            field=models.TextField(default='Качественное турецкое постельное белье от официального диллера', verbose_name='Текст оффера'),
        ),
    ]
