# Generated by Django 3.2 on 2021-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_offertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timerDays',
            field=models.IntegerField(default=1, verbose_name='Сколько дней на таймере'),
        ),
    ]
