# Generated by Django 3.2 on 2021-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210424_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='feedback/', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': '5. Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '3. Товары'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '2. Размеры'},
        ),
    ]
