# Generated by Django 3.2 on 2021-04-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210424_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='api.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать ?'),
        ),
    ]
