# Generated by Django 3.2 on 2021-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210424_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='feedback/', verbose_name='Картинка отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать отзыв?'),
        ),
    ]
