# Generated by Django 3.2 on 2021-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210425_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='Цена'),
        ),
    ]
