# Generated by Django 3.2 on 2021-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210425_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='selected_size',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
