# Generated by Django 3.2 on 2021-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_item_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='selected_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ostatok',
            name='is_size_set',
            field=models.BooleanField(default=False),
        ),
    ]
