# Generated by Django 3.2 on 2021-04-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210425_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offerImageMobile',
            field=models.ImageField(null=True, upload_to='category/', verbose_name='Бекграунд оффера мобильный'),
        ),
    ]
