# Generated by Django 3.2 on 2021-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_offerimagemobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='amokey',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
