# Generated by Django 3.2 on 2021-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_amokey_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='amokey',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
