# Generated by Django 3.2 on 2021-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_amokey_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='showPromoBlock',
            field=models.BooleanField(default=False, verbose_name='Показывать промо блок?'),
        ),
    ]
