# Generated by Django 3.2 on 2021-04-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_category_showpromoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_show_at_thanks_page',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать на странице спасибо ?'),
        ),
    ]
