# Generated by Django 3.2 on 2021-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_item_is_show_at_thanks_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0, verbose_name='Цена для смтраницы спасибо'),
        ),
    ]
